version: '3.8'
services:
  spaceship-api:
    build: .
    container_name: spaceship
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spaceship-network
    depends_on:
      - db

  db:
    image: oscarfonts/h2
    container_name: spaceship-db
    ports:
      - "9092:9092"
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - spaceship-network

networks:
  spaceship-network:
    driver: bridge